/**
 * Roke.to
 * The best realtime streaming solution
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AccessTokenDto {
    /**
    * JWT to use in bearer authorization
    */
    'accessToken': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccessTokenDto.attributeTypeMap;
    }

    public constructor() {
    }
}

