/**
 * Roke.to
 * The best realtime streaming solution
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LoginDto {
    /**
    * The accountId of a user.
    */
    'accountId': string;
    /**
    * Login message starting with \"ROKETO-LOGIN\" and ending with current timestamp
    */
    'message': string;
    /**
    * Signature of login message signed with user's private key in form of an array of 64 integer numbers
    */
    'signature': Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LoginDto.attributeTypeMap;
    }

    public constructor() {
    }
}

