/**
 * Roke.to
 * The best realtime streaming solution
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateUserDto {
    /**
    * The name of a user.
    */
    'name'?: string;
    /**
    * The email of a user.
    */
    'email'?: string;
    /**
    * User's allowance for email notifications.
    */
    'allowNotifications'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "allowNotifications",
            "baseName": "allowNotifications",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateUserDto.attributeTypeMap;
    }

    public constructor() {
    }
}

